name: Deploy to AWS

on:
  push:
    branches: [ "main" ] # Se lance quand on envoie le code

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # 1. On arrête l'ancienne version si elle existe
            sudo docker stop sentinel || true
            sudo docker rm sentinel || true

            # 2. On télécharge le code
            # Si le dossier n'existe pas, on le clone (CHANGE LE PSEUDO ICI !)
            if [ ! -d "cloud-sentinel" ]; then
              git clone https://github.com/wiameMakmouli/cloud-sentinel.git
            fi
            
            # On entre dans le dossier et on met à jour
            cd cloud-sentinel
            git pull origin main
            
            # 3. On construit la nouvelle version
            cd app
            sudo docker build -t sentinel-app .
            
            # 4. On lance l'application sur le port 80 (Web)
            sudo docker run -d -p 80:80 --name sentinel sentinel-app
